spring:
  application.name: ms1
  profiles.active: dev
  config.import: optional:configserver:http://admin:1234@localhost:9000

eureka.client:
  registerWithEureka: true #유레카 서버에 등록할지 여부
  fetchRegistry: true #유레카 서버의 정보를 가져올지 여부
  serviceUrl:
    defaultZone: http://admin:1234@localhost:8761/eureka #유레카 서버 주소

server:
  port: 8081


resilience4j:
  retry:
    instances:
      retry:
        baseConfig: default
    configs:
      default:
        max-attempts: 3
        wait-duration: 3000ms

  circuitbreaker:
    instances:
      fail:
        baseConfig: default

    configs:
      default:
        sliding-window-type: count_based
        slidingWindowSize: 5

        failure-rate-threshold: 10
        minimum-number-of-calls: 5

        slow-call-rate-threshold: 10
        slow-call-duration-threshold: 3000ms

        permitted-number-of-calls-in-half-open-state: 10
        max-wait-duration-in-half-open-state: 0

        wait-duration-in-open-state: 10000ms
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true


management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always


  health:
    circuitbreakers:
      enabled: true