server:
  port: 8080

spring:
  application:
    name: gateway

eureka.client:
  registerWithEureka: true #유레카 서버에 등록할지 여부
  fetchRegistry: true #유레카 서버의 정보를 가져올지 여부
  serviceUrl:
    defaultZone: http://admin:1234@localhost:8761/eureka #유레카 서버 주소
